apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: manifests
    environment: production
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin
