apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: manifests
    environment: production
