apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: manifests
    environment: production
