apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: manifests
    environment: production
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: "prometheus"
      static_configs:
      - targets: ["localhost:9090"]

    - job_name: "kube-state-metrics"
      static_configs:
      - targets: ["kube-state-metrics.monitoring.svc.cluster.local:8080"]

    - job_name: "node-exporter"
      static_configs:
      - targets: ["node-exporter.monitoring.svc.cluster.local:9100"]
