apiVersion: v1
kind: Service
metadata:
  name: journal-db
  labels:
    app.kubernetes.io/name: journal-db
    app.kubernetes.io/instance: journal
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: journal
    app.kubernetes.io/managed-by: manifests
    environment: production
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: journal-db
    app.kubernetes.io/instance: journal
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
