apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: journal
  namespace: default
  labels:
    app.kubernetes.io/name: journal
    app.kubernetes.io/instance: journal
    app.kubernetes.io/version: "3.0"
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: journal
    app.kubernetes.io/managed-by: manifests
    environment: production
spec:
  encryptedData:
    API_KEY: ""
    DB_PASSWORD: ""
    DATABASE_URL: ""
