apiVersion: v1
kind: Service
metadata:
  name: journal
  labels:
    app.kubernetes.io/name: journal
    app.kubernetes.io/instance: journal
    app.kubernetes.io/version: "3.0"
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: journal
    app.kubernetes.io/managed-by: manifests
    environment: production
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: journal
    app.kubernetes.io/instance: journal
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
